[package]
edition = "2021"

name = "vsmtp"
version = "0.7.1"
license = "GPLv3"

authors = ["Team viridIT <https://viridit.com/>"]
description = "vSMTP : the next-gen MTA. Secured, Faster and Greener"
homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"

publish = false

[dependencies]
log = "0.4.14"
log4rs = { version = "1.0" }

# config = { version = "0.11.0", features = ["toml"] }
clap = "2.34.0"
# inactive since Oct. 2020
users = "0.11"
libc = "0.2"

## Parser / Serializer
serde = { version = "1.0.130", features = ["derive"] }
serde_derive = "1.0.130"
serde_with = { version = "1.11.0", features = ["macros"] }
serde_json = "1.0.72"

toml = "0.5.8"
humantime = "2.1.0"
humantime-serde = "1.0.1"
addr = { version = "0.15.0" }
regex = "1.5.4"
iprange = "0.6.6"
ipnet = "2.3.1"
chrono = "0.4"

rhai = { version = "1.1.0", features = ["unchecked", "sync"] }

# the 0.10 release is more stable than the 0.9 and enable async support.
lettre = "0.10.0-rc.4"

async-trait = "0.1.51"
lazy_static = "1.4"

rustls = { version = "0.20.0", features = ["tls12", "logging"] }
rustls-pemfile = "0.2.1"

tokio = { version = "1.14.0", features = ["full"] }

[dev-dependencies]
criterion = { version = "0.3.5", features = ["async_tokio"] }
fork = "0.1.18"
rand = "0.8.4"

[[bench]]
name = "receiver"
harness = false
