version_requirement = "<1.0.0"

[server]
domain = "testserver.com"

[server.tls]
security_level = "May"
preempt_cipherlist = false
handshake_timeout = "200ms"
protocol_version = "TLSv1.3"
certificate = "../examples/config/tls/certificate.crt"
private_key = "../examples/config/tls/private_key.key"

[server.virtual."testserver1.com"]

[server.virtual."testserver2.com".dns]
type = "system"

[server.virtual."testserver3.com".tls]
protocol_version = "TLSv1.3"
certificate = "../examples/config/tls/certificate.crt"
private_key = "../examples/config/tls/private_key.key"

[server.virtual."testserver4.com".tls]
protocol_version = "TLSv1.3"
certificate = "../examples/config/tls/certificate.crt"
private_key = "../examples/config/tls/private_key.key"

[server.virtual."testserver4.com".dns]
type = "google"
