### See vsmtp.default.toml documentation for this file format

version = "0.1.0"
domain = "mydomain.com"

[server]
addr = ["127.0.0.1:25"]

[log]
file = "/var/log/vsmtp/vsmtp.log"

[log.level]
default = "warn"
rules = "warn"
receiver = "info"

[rules]
dir = "/etc/vsmtp/rules"

[tls]
security_level = "May"
capath = "/etc/vsmtp/certs"
preempt_cipherlist = true
handshake_timeout = "100ms"

[[tls.sni_maps]]
domain = "testserver.com"
fullchain = "{capath}/fullchain.{domain}.pem"
private_key = "{capath}/rsa.{domain}.pem"

[smtp]
spool_dir = "/var/spool/vsmtp"

[smtp.timeout_client]
Helo = "10000ms"
Data = "10000ms"

[smtp.error]
soft_count = 5
hard_count = 10
delay = "5000ms"
