[package]
edition = "2021"

name = "vsmtp-config"
version = "0.9.5"
license = "GPLv3"

authors = ["Team viridIT <https://viridit.com/>"]
description = "vSMTP : the next-gen MTA. Secured, Faster and Greener"
homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"

publish = false

[dependencies]
vsmtp-common = { version = "^0.9", path = "../vsmtp-common" }

libc = "0.2.109"

log = "0.4.14"
log4rs = { version = "1.0.0" }

anyhow = "1.0.56"

users = { version = "0.11.0", features = [] }

serde = { version = "1.0.136", features = ["derive"] }
serde_derive = "1.0.136"
serde_with = { version = "1.12.0", features = ["macros"] }
humantime-serde = "1.1.1"

toml = "0.5.8"

enum-iterator = "0.7.0"

rustls = { version = "0.20.4", features = ["tls12", "logging"] }
rustls-pemfile = "0.3.0"

num_cpus = "1.13.1"
hostname = "0.3.1"

semver = "1.0.6"


[dev-dependencies]
pretty_assertions = "1.1.0"

serde_json = "1.0.79"
